POST http://localhost:3000/gnurun/fulfillment-order
content-type: application/json

{
  "id": 6774,
  "created_at": "2026-01-09T02:50:10",
  "updated_at": null,
  "customer_id": 56,
  "customer": {
    "customer_id": 56,
    "company_id": 142,
    "company_name": "TEST-USER"
  },
  "current_wh": 1,
  "warehouse": "Test 1",
  "address": {
    "business_name": null,
    "reference_name": "Anthony Rodelli",
    "address": "",
    "city": "Clinton",
    "street": ", 11545 Destination Dr Apt 3315, ",
    "province": "AR",
    "country": "United States",
    "zip_code": "72031-8604",
    "email": "cusa.q7yw1pterfxt9iqm@marketplace.newegg.com",
    "tel": "720-377-6795"
  },
  "status": "CONFIRMED",
  "extra_data": {
    "courier_data": {
      "courier_name": "",
      "courier_tracking": ""
    },
      "customer_reference": "553144651-2500019927",
      "reference_name": "Anthony Rodelli",
      "provider": "GNURUN console"
  },
  "products": [
    {
      "product_id": 3292,
      "product_sku": "TEST-56",
      "sku_code": "test123456",
      "product_name": "test",
      "product_position": "TT030303",
      "height": 0.1,
      "width": 0.1,
      "length": 0.1,
      "weight": 0.1,
      "note": null,
      "stock": 1,
      "qty_order": 1,
      "positions": [
        {
          "product_id": 3292,
          "wh_id": 1,
          "delivery_id": 1725,
          "wh_position": "TT030303",
          "stock": 1
        }
      ],
      "stocked_product_id": 1226,
      "picked_qty": 0,
      "missing_qty": 0
    }],
  "cost": null,
  "note": "",
  "warehouse_note": "",

  "files": [],
  "invoice_n": null,
  "billing_cycle": null
}
