POST http://localhost:3000/gnurun/fulfillment-order
content-type: application/json

{
  "id": 363,
  "created_at": "2024-10-09T15:36:55",
  "updated_at": null,
  "customer_id": 1,
  "customer": {
    "customer_id": 1,
    "company_id": 1,
    "company_name": "Life365 Italy TEST"
  },
  "current_wh": 1,
  "address": {
    "business_name": "Vincenzo Tumminello",
    "reference_name": "Vincenzo Tumminello",
    "address": "",
    "city": "Patrica",
    "street": "Ettore Marchiafava 24",
    "province": "FR",
    "country": "IT",
    "zip_code": "03010",
    "email": 123,
    "tel": 390775222072
  },
  "status": "CONFIRMED",
  "extra_data": {
    "courier_data": {
      "courier_name": "",
      "courier_tracking": ""
    },
    "customer_reference": 123,
    "reference_name": "Vincenzo Tumminello",
    "provider": null
  },
  "products": [
    {
      "product_id": 2098,
      "product_sku": "TESTEE008",
      "product_name": "TESTEE008",
      "product_position": "BB010102",
      "height": 5,
      "width": 30,
      "length": 30,
      "weight": 0.9,
      "note": "",
      "stock": 10,
      "positions": [
        {
          "product_id": 2098,
          "wh_id": 1,
          "delivery_id": 315,
          "wh_position": "BB010102",
          "stock": 5
        },
        {
          "product_id": 2098,
          "wh_id": 1,
          "delivery_id": 315,
          "wh_position": "BB010103",
          "stock": 5
        }
      ]
    }],
  "cost": null,
  "note": "",
  "warehouse_note": "",

  "files": [],
  "invoice_n": null,
  "billing_cycle": null
}

