POST http://localhost:3000/gnurun/print/delivery
content-type: application/json

{
  "id": 425,
  "company_id": 1,
  "customer_id": 1,
  "warehouse_id": 1,
  "d_state": "INVOICED",
  "creation_date": "2025-01-15T11:29:02+00:00",
  "wh_note": "wqewqewq",
  "invoice_n": 104,
  "courier_name": "test0115",
  "courier_tracking": "01152025",
  "boxes": [
    {
      "id": 452,
      "delivery_id": 425,
      "box_height_cm": "3.2",
      "box_length_cm": "5.6",
      "box_width_cm": "5.6",
      "box_weight_kg": "1.223",
      "box_qty": 1,
      "products": [
        {
          "id": 1051,
          "wh_delivery_box_id": 452,
          "product_id": 2192,
          "quantity": 30,
          "p_code": "TEST0115",
          "p_position": "AA1122VV",
          "p_unit_type": "PIECE",
          "p_weight_kg": 1,
          "p_height_cm": 14,
          "p_length_cm": 21,
          "p_width_cm": 11
        }
      ]
    },
    {
      "id": 452,
      "delivery_id": 425,
      "box_height_cm": "6.2",
      "box_length_cm": "2.6",
      "box_width_cm": "6.6",
      "box_weight_kg": "4.223",
      "box_qty": 1,
      "products": [
        {
          "id": 1051,
          "wh_delivery_box_id": 452,
          "product_id": 2192,
          "quantity": 30,
          "p_code": "TEST0115",
          "p_position": "AA1122VV",
          "p_unit_type": "PIECE",
          "p_weight_kg": 1,
          "p_height_cm": 14,
          "p_length_cm": 21,
          "p_width_cm": 11
        }
      ]
    }
  ],
  "cost": {
    "shipping_cost": "0",
    "inner_cost": [
      {
        "id": 23,
        "descr": "Inbound fee",
        "qty": 1,
        "cost": "1"
      },
      {
        "id": 24,
        "descr": "Check fee",
        "qty": 20,
        "cost": "2"
      }
    ]
  },
  "billing_cicle": null
}
