POST http://localhost:3000/gnurun/delivery
content-type: application/json

{
  "id": 425,
  "company_id": 1,
  "customer_id": 1,
  "warehouse_id": 1,
  "d_state": "INVOICED",
  "creation_date": "2025-01-15T11:29:02+00:00",
  "wh_note": "wqewqewq",
  "invoice_n": 104,
  "courier_name": "test0115",
  "courier_tracking": "01152025",
  "company_name": "Life365 Italy",
  "boxes": [
    {
      "id": 452,
      "delivery_id": 425,
      "box_height_cm": "3.2",
      "box_length_cm": "5.6",
      "box_width_cm": "5.6",
      "box_weight_kg": "1.223",
      "box_qty": 1,
      "products": [
        {
          "id": 1051,
          "wh_delivery_box_id": 452,
          "product_id": 2192,
          "quantity": 30,
          "p_code": "TEST0115",
          "p_title": "Test product",
          "p_position": "",
          "p_unit_type": "PIECE",
          "p_weight_kg": 1,
          "p_height_cm": 14,
          "p_length_cm": 21,
          "p_width_cm": 11,
          "sku_code": "SKU-0115",
          "product_name": "Test product",
          "description": "Test product description",
          "in_stock": 0
        }
      ]
    },
    {
      "id": 453,
      "delivery_id": 425,
      "box_height_cm": "6.2",
      "box_length_cm": "2.6",
      "box_width_cm": "6.6",
      "box_weight_kg": "4.223",
      "box_qty": 1,
      "products": [
        {
          "id": 1052,
          "wh_delivery_box_id": 453,
          "product_id": 2192,
          "quantity": 30,
          "p_code": "TEST0115",
          "p_title": "Test product",
          "p_position": "",
          "p_unit_type": "PIECE",
          "p_weight_kg": 1,
          "p_height_cm": 14,
          "p_length_cm": 21,
          "p_width_cm": 11,
          "sku_code": "SKU-0115",
          "product_name": "Test product",
          "description": "Test product description",
          "in_stock": 0
        }
      ]
    }
  ]
}
