POST http://localhost:3000/gnurun/delivery-label
content-type: application/json

{
  "id": 4,
  "customer_id": 1,
  "boxes": [
    {
      "products": [
        {
          "code": "XLBBS0003",
          "qty": 40
        }
      ],
      "weight": "17.900",
      "box_qty": 8
    },
    {
      "products": [
        {
          "code": "FM8005",
          "qty": 30
        }
      ],
      "weight": "15.000",
      "box_qty": 10
    }
  ]
}
